package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Conversation struct{ID int64 `json:"id"`;Visitor string `json:"visitor"`;Page string `json:"page"`;Status string `json:"status"`;MessageCount int `json:"message_count"`;CreatedAt time.Time `json:"created_at"`}
type Message struct{ID int64 `json:"id"`;ConversationID int64 `json:"conversation_id"`;Sender string `json:"sender"`;Body string `json:"body"`;SentAt time.Time `json:"sent_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"parlor.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS conversations(id INTEGER PRIMARY KEY AUTOINCREMENT,visitor TEXT DEFAULT 'anonymous',page TEXT DEFAULT '/',status TEXT DEFAULT 'open',message_count INTEGER DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,conversation_id INTEGER NOT NULL,sender TEXT NOT NULL,body TEXT NOT NULL,sent_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)CreateConversation(visitor,page string)(*Conversation,error){res,err:=db.Exec(`INSERT INTO conversations(visitor,page)VALUES(?,?)`,visitor,page);if err!=nil{return nil,err};id,_:=res.LastInsertId();return &Conversation{ID:id,Visitor:visitor,Page:page,Status:"open"},nil}
func(db *DB)ListConversations()([]Conversation,error){rows,_:=db.Query(`SELECT c.id,c.visitor,c.page,c.status,COUNT(m.id),c.created_at FROM conversations c LEFT JOIN messages m ON m.conversation_id=c.id GROUP BY c.id ORDER BY c.created_at DESC LIMIT 100`);defer rows.Close();var out[]Conversation;for rows.Next(){var c Conversation;rows.Scan(&c.ID,&c.Visitor,&c.Page,&c.Status,&c.MessageCount,&c.CreatedAt);out=append(out,c)};return out,nil}
func(db *DB)AddMessage(m *Message)error{res,err:=db.Exec(`INSERT INTO messages(conversation_id,sender,body)VALUES(?,?,?)`,m.ConversationID,m.Sender,m.Body);if err!=nil{return err};m.ID,_=res.LastInsertId();db.Exec(`UPDATE conversations SET message_count=message_count+1 WHERE id=?`,m.ConversationID);return nil}
func(db *DB)GetMessages(convID int64)([]Message,error){rows,_:=db.Query(`SELECT id,conversation_id,sender,body,sent_at FROM messages WHERE conversation_id=? ORDER BY sent_at`,convID);defer rows.Close();var out[]Message;for rows.Next(){var m Message;rows.Scan(&m.ID,&m.ConversationID,&m.Sender,&m.Body,&m.SentAt);out=append(out,m)};return out,nil}
func(db *DB)CloseConversation(id int64){db.Exec(`UPDATE conversations SET status='closed' WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var open,total int;db.QueryRow(`SELECT COUNT(*) FROM conversations WHERE status='open'`).Scan(&open);db.QueryRow(`SELECT COUNT(*) FROM conversations`).Scan(&total);return map[string]interface{}{"open_conversations":open,"total_conversations":total},nil}
